ENV['VAGRANT_SERVER_URL'] = 'http://kerberos:8099'

Vagrant.configure("2") do |config|
  config.vm.box = "clerabe/ubuntu-14.04.5-server-amd64-daily"
  config.vm.synced_folder "../", "/vagrancy"
  config.vm.provision :shell, path: "provisioning.sh", privileged: false
end
